# Generated by Django 4.1.9 on 2023-05-31 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('valid_from', models.DateTimeField(verbose_name='Действителен от')),
                ('valid_to', models.DateTimeField(verbose_name='Действителен до')),
                ('discount', models.IntegerField(help_text='Процентное значение (от 0 до 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка')),
                ('active', models.BooleanField(verbose_name='Активный')),
            ],
        ),
    ]
